name: Deploy Frontend

on:
  push:
    branches:
      - dev
    paths:
      - 'frontend/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Frontend Files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/*"
          target: "/tmp/frontend"

      - name: Deploy Frontend to Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r /tmp/frontend/* /var/www/html/
            sudo systemctl restart nginx

            echo "Frontend deployed successfully."