name: Deploy to Development

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t divaypratap/employee-management-app:dev .

      - name: Push Docker Image
        run: |
          docker push divaypratap/employee-management-app:dev

      - name: Deploy to Development Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_SSH_KEY }}

          script: |
            docker pull divaypratap/employee-management-app:dev

            docker stop employee-app || true

            docker rm employee-app || true

            docker run -d \
              --name employee-app \
              --restart unless-stopped \
              -e MONGO_URI="${{ secrets.MONGO_URI }}" \
              -p 5000:5000 \
              divaypratap/employee-management-app:dev